### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tchesket** [Raemien/BeatSaberCustomBackgrounds#1]
Hey, I love this tool, great work! I'm not really having any issues per se, but I had a question. I could be way off base here, but what I did was created a panoramic photo of the inside of my house where I stand to play beat saber. This worked and everything, but the issue is that it places me floating in mid-air and at half my normal height etc. I didn't know if it was possible to adjust the image somehow as to make it appear like it does in real life, or not.

**Comment by Raemien** [comment]
Thanks for getting in touch! There are a few things that might help with matching the panoramic background to your room:
- Try converting the panorama to a cubemap, then an equiangular texture. This usually helps with applying distortions to an image.
- Make sure the panorama is taken close to eye level.

Let me know if these tips help with your issue. Alternatively, I've been working on an AR project that sets the HTC Vive's camera as the background, which may achieve a similar result.

**Comment by tchesket** [comment]
Thanks I will try that and update on how it goes. Just to be clear, you're saying the end-result should appear in-game the same as it does in real life/regular vision (from perspective and scale)? I used the Google Street View app's panoramic 360 image function (photosphere) to create the equirectangular image in question, if that means anything to you. Thanks for your help

**Comment by tchesket** [comment]
Hmm okay I tried what you said to do, using the conversion tool linked to on this github, the cubemap came out looking extremely distorted, and converting back into equirectangular also looked very distorted. The preview function of the tool looks normal with the original image, I'm not sure what exactly I'm doing wrong here.
