### ISSUE TITLE
Possible on the PC version?!?

### ISSUE THREAD

**Issue by Theguru123** [Raemien/BeatSaberCustomBackgrounds#2]
Hi there is there anyway this could be ported to the PC by any chance..I use the quest version and it works a treat..would love if it was ported to the PC though!!

**Comment by Raemien** [comment]
Hi there! Funnily enough, this repo is actually for the PC version of Custom Backgrounds.
While I'm not too sure when I'll be able to update this, most of the code requires an overhaul due to the project being over a year old.

**Comment by Theguru123** [comment]
Oh ok doh! On my part..well if there is any chance it could be done that would be great!!  I suppose it doesn’t beat saber keeps updating!!!! I follow the discord and I assumed this was the quest!! Keep up the good work!!
